
# Use the official ASP.NET SDK image for building
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8.1 AS build
RUN mkdir app
RUN cmd /S /C "icacls C:\app /grant Everyone:(OI)(CI)F"
WORKDIR /app

# copy csproj and restore as distinct layers
COPY WebAppl5.sln .
COPY WebAppl5/*.csproj ./WebAppl5/
COPY WebAppl5/*.config ./WebAppl5/
RUN nuget restore WebAppl5.sln

# copy SourceCode and build app
COPY WebAppl5/. ./WebAppl5/
WORKDIR /app/WebAppl5
RUN msbuild /p:Configuration=Release -r:False

## Create application image on official ASP.NET runtime image
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8.1 AS runtime

# Install Chocolatey
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command ` \
    "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"; ` \
  iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

#Install git bash and sqlcmd
RUN choco install -y sqlcmd

#######SDK################ https://github.com/microsoft/dotnet-framework-docker/blob/fde8008601b667cba71f53a02d9e64884603d8bf/src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile

SHELL ["cmd", "/S", "/C"]

# Install NuGet CLI
RUN mkdir "%ProgramFiles%\NuGet\latest" && \
    curl -fSLo "%ProgramFiles%\NuGet\nuget.exe" https://dist.nuget.org/win-x86-commandline/v6.8.0/nuget.exe && \
    mklink "%ProgramFiles%\NuGet\latest\nuget.exe" "%ProgramFiles%\NuGet\nuget.exe"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install VS Test Agent
RUN Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_TestAgent.exe -OutFile vs_TestAgent.exe; ` \
    Start-Process -Wait -FilePath .\vs_TestAgent.exe -ArgumentList "--quiet --norestart --nocache --installPath `"${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\TestAgent`""; ` \
    if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }; ` \
    Remove-Item -Force vs_TestAgent.exe

# Install VS Build Tools
RUN Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_BuildTools.exe; \
    start /w vs_BuildTools ^ \
        --installPath "$Env:ProgramFiles(x86)\Microsoft Visual Studio\2022\BuildTools" ^ \
        --add Microsoft.Component.ClickOnce.MSBuild ^ \
        --add Microsoft.Net.Component.4.8.1.SDK ^ \
        --add Microsoft.NetCore.Component.Runtime.6.0 ^ \
        --add Microsoft.NetCore.Component.Runtime.7.0 ^ \
        --add Microsoft.NetCore.Component.Runtime.8.0 ^ \
        --add Microsoft.NetCore.Component.SDK ^ \
        --add Microsoft.VisualStudio.Component.NuGet.BuildTools ^ \
        --add Microsoft.VisualStudio.Component.WebDeploy ^ \
        --add Microsoft.VisualStudio.Web.BuildTools.ComponentGroup ^ \
        --add Microsoft.VisualStudio.Workload.MSBuildTools ^ \
        --quiet --norestart --nocache --wait; \
    if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }; \
    Remove-Item -Force vs_BuildTools.exe

# Trigger dotnet first run experience by running arbitrary cmd
RUN "%ProgramFiles%\dotnet\dotnet" help

# Workaround for issues with 64-bit ngen
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen uninstall "$Env:ProgramFiles(x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\SecAnnotate.exe"; \
    %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen uninstall "$Env:ProgramFiles(x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\WinMDExp.exe"

# ngen assemblies queued by VS installers
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen update

# Cleanup
RUN Remove-Item -Force -Recurse "$Env:TEMP\*" ; \
    Remove-Item -Force -Recurse "$Env:ProgramFiles(x86)\Microsoft Visual Studio\Installer\*" ; \
    Remove-Item -Force -Recurse "$Env:ProgramData\Package Cache" ; \
    Remove-Item -Force -Recurse "$Env:ProgramData\Microsoft\VisualStudio\Packages" ; \
    Remove-Item -Force -Recurse "$Env:ProgramData\chocolatey"

# Set PATH in one layer to keep image size down.
RUN set "PATH=%PATH%;%ProgramFiles%\NuGet;%ProgramFiles(x86)%\Microsoft Visual Studio\2022\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow;%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64;%ProgramFiles(x86)%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools;%ProgramFiles(x86)%\Microsoft SDKs\ClickOnce\SignTool"

# Install Targeting Packs
RUN set "ErrorActionPreference=Stop" && set "ProgressPreference=SilentlyContinue" && ` \
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v4.0" -OutFile referenceassemblies_4.0.zip && ` \
    Expand-Archive referenceassemblies_4.0.zip -DestinationPath "%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework" && ` \
    Remove-Item -Force referenceassemblies_4.0.zip

RUN set "ErrorActionPreference=Stop" && set "ProgressPreference=SilentlyContinue" && ` \
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v4.5.2" -OutFile referenceassemblies_4.5.2.zip && ` \
    Expand-Archive referenceassemblies_4.5.2.zip -DestinationPath "%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework" && ` \
    Remove-Item -Force referenceassemblies_4.5.2.zip

RUN set "ErrorActionPreference=Stop" && set "ProgressPreference=SilentlyContinue" && ` \
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v4.6.2" -OutFile referenceassemblies_4.6.2.zip && ` \
    Expand-Archive referenceassemblies_4.6.2.zip -DestinationPath "%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework" && ` \
    Remove-Item -Force referenceassemblies_4.6.2.zip

RUN set "ErrorActionPreference=Stop" && set "ProgressPreference=SilentlyContinue" && ` \
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v4.7.2" -OutFile referenceassemblies_4.7.2.zip && ` \
    Expand-Archive referenceassemblies_4.7.2.zip -DestinationPath "%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework" && ` \
    Remove-Item -Force referenceassemblies_4.7.2.zip

RUN set "ErrorActionPreference=Stop" && set "ProgressPreference=SilentlyContinue" && ` \
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v4.8" -OutFile referenceassemblies_4.8.zip && ` \
    Expand-Archive referenceassemblies_4.8.zip -DestinationPath "%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework" && ` \
    Remove-Item -Force referenceassemblies_4.8.zip

RUN set "ErrorActionPreference=Stop" && set "ProgressPreference=SilentlyContinue" && ` \
    Invoke-WebRequest -UseBasicParsing -Uri "https://dotnetbinaries.blob.core.windows.net/referenceassemblies/v4.8.1" -OutFile referenceassemblies_4.8.1.zip && ` \
    Expand-Archive referenceassemblies_4.8.1.zip -DestinationPath "%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework" && ` \
    Remove-Item -Force referenceassemblies_4.8.1.zip
#######SDK################

WORKDIR /inetpub/wwwroot
COPY --from=build /app/WebAppl5/. ./
