
# Use the official ASP.NET SDK image for building
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8.1 AS build
RUN mkdir app
RUN cmd /S /C "icacls C:\app /grant Everyone:(OI)(CI)F"
WORKDIR /app

# copy csproj and restore as distinct layers
COPY WebAppl5.sln .
COPY WebAppl5/*.csproj ./WebAppl5/
COPY WebAppl5/*.config ./WebAppl5/
RUN nuget restore WebAppl5.sln

# copy SourceCode and build app
COPY WebAppl5/. ./WebAppl5/
WORKDIR /app/WebAppl5
RUN msbuild /p:Configuration=Release -r:False

## Create application image on official ASP.NET runtime image
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8.1 AS runtime

# Install Chocolatey
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command ` \
    "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072"; ` \
  iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

#Install git bash and sqlcmd
RUN choco install -y sqlcmd dotnet-7.0-sdk

# Install Git and its BASH terminal for UNIX extras
RUN choco install -y git
RUN setx path "C:\\Program Files\\Git\\bin;%path%"

# Install troubleshooting tools using chocolatey
RUN choco install -y procmon dbgview tcping

# Additional network troubleshooting tools
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command Install-WindowsFeature -Name Telnet-Client
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command Install-WindowsFeature RSAT-DNS-Server
# RUN powershell -NoProfile -ExecutionPolicy Bypass -Command Install-WindowsFeature -Name RSAT-Net Cmdlets

# Trials
# # Install SQL Server command-line utilities
# RUN curl -o SQLServerClientTools.msi https://go.microsoft.com/fwlink/?linkid=2230791
# RUN powershell -Command Start-Process -Wait -FilePath msiexec -ArgumentList '/i', 'C:\SQLServerClientTools.msi', '/qn'
# RUN del C:\SQLServerClientTools.msi

# # Install Telnet
# RUN dism /Online /Enable-Feature /FeatureName:TelnetClient

# Install git for Windows to get Bash terminal
# SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# RUN Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.42.0.windows.1/Git-2.42.0-64-bit.exe -OutFile git.exe -UseBasicParsing; \
#     Start-Process -Wait -FilePath .\git.exe -ArgumentList '/VERYSILENT', '/NORESTART', '/NOICONS', '/NOCANCEL', '/SP-', '/DIR=C:\Git'; \
#     Remove-Item -Force git.exe
##### Trials

WORKDIR /inetpub/wwwroot
COPY --from=build /app/WebAppl5/. ./

#Use below lines for bash terminal on container
# SHELL ["bash.exe", "-c"]
# RUN "ls -la"
# ENTRYPOINT ["bash.exe"]

